//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Draw.rc
//
#define IDR_DRAWTYPE_SRVR_IP            4
#define IDR_DRAWTYPE_SRVR_EMB           5
#define IDR_DRAWTYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDW_TOOLBOX_BAR                 101
#define IDP_FAILED_TO_CREATE            102
#define ID_LINESTYLE                    102
#define IDR_MAINFRAME                   128
#define IDR_DRAWTYPE                    129
#define IDB_IMGLIST_TAB                 130
#define IDB_IMGLIST_VIEW                131
#define IDD_SUMM_PAGE                   140
#define IDD_STAT_PAGE                   141
#define IDR_TOOLBAR_BOX                 142
#define IDR_FORMATTING                  144
#define IDR_BORDERS                     146
#define IDR_LINE_WIDTH                  151
#define ID_POPUP_MENU                   153
#define IDC_PENCIL                      154
#define IDD_PROP_RECT                   155
#define IDB_ARROWS                      157
#define IDD_FILL_DLG                    158
#define IDD_FILL_GRADIENT               159
#define IDD_FILL_PATTERN                160
#define IDD_DIALOG_ACTION               161
#define IDB_LINESTYLE                   162
#define IDC_ZOOMCURSOR1                 167
#define IDC_ZOOMCURSOR                  168
#define IDD_DIALOG_TEXT                 169
#define IDD_DIALOG_GROUP                171
#define IDD_DIALOG_NEW_DOC              172
#define IDD_INSERTCONTROL               173
#define IDR_TREE_POPUP                  174
#define IDD_DIALOG_HOST_SETTING         175
#define IDD_DIALOG_SET_TIMER            176
#define IDB_TABS                        177
#define IDB_HEADER                      178
#define IDD_DIALOGBAR                   179
#define IDI_ICON1                       180
#define IDI_ICON2                       181
#define IDI_ICON3                       182
#define IDI_ICON4                       183
#define IDI_ICON5                       184
#define IDI_ICON6                       185
#define IDI_ICON7                       186
#define IDI_ICON8                       187
#define IDI_ICON9                       188
#define IDD_FORMVIEW                    189
#define IDD_MANIPULATE                  190
#define IDD_FLATTAB_PROP                191
#define IDC_APPNAME                     1004
#define IDC_AUTHOR                      1005
#define IDC_KEYWORDS                    1006
#define IDC_COMMENTS                    1007
#define IDC_TITLE                       1008
#define IDC_SUBJECT                     1009
#define IDC_TEMPLATE                    1010
#define IDC_FTS_XT_HASARROWS            1010
#define IDC_SAVEDBY                     1011
#define IDC_FTS_XT_HASHOMEEND           1011
#define IDC_REVNUM                      1012
#define IDC_FTS_XT_HSCROLL              1012
#define IDC_EDITTIME                    1013
#define IDC_FTS_XT_BOTTOM               1013
#define IDC_LASTPRINT                   1014
#define IDC_CREATEDATE                  1015
#define IDC_LASTSAVE                    1016
#define IDC_NUMPAGES                    1017
#define IDC_NUMWORDS                    1018
#define IDC_NUMCHARS                    1019
#define IDC_MANIPULATE                  1019
#define IDC_SECURITY                    1020
#define IDC_DELETE_ALL                  1020
#define IDC_FILL_COLOR                  1021
#define IDC_TAB_NUM                     1021
#define IDC_TEXT                        1022
#define IDC_DELETE_TAB                  1023
#define IDC_EDIT_TRANS                  1024
#define IDC_MODIFY_TAB                  1024
#define IDC_SPIN_TRANS                  1025
#define IDC_ADD_TAB                     1025
#define IDC_LINE_SIZE                   1027
#define IDC_SPIN_LINESIZE               1028
#define IDC_ARROW_START_SIZE            1029
#define IDC_LINE_COLOR                  1031
#define IDC_TAB1                        1033
#define IDC_SPIN_START_SIZE             1033
#define IDC_BUTTON_ONE_COLOR            1036
#define IDC_ARROW_END_SIZE              1037
#define IDC_BUTTON2                     1037
#define IDC_SPIN_END_SIZE               1038
#define IDC_LIST_INFO                   1045
#define IDC_RADIO_SHUIPING              1047
#define IDC_BUTTON_FORWD_COLOR          1048
#define IDC_RADIO_CHUIZHI               1048
#define IDC_NoFill                      1049
#define IDC_BUTTON_BACK_COLOR           1049
#define IDC_RADIO_DUIJIAO_UP            1049
#define IDC_LIST_HISTORY                1049
#define IDC_COMBO_LINESTYLE             1050
#define IDC_RADIO_RIGHT_UP              1050
#define IDC_RADIO7                      1051
#define IDC_COMBO_ARROW_START_STYLE     1051
#define IDC_RADIO8                      1052
#define IDC_COMBO_ARROW_END_STYLE       1052
#define IDC_BUTTON_WELL                 1053
#define IDC_RADIO9                      1053
#define IDC_BUTTON_TWO_COLOR            1054
#define IDC_TAB_INFO                    1054
#define IDC_BUTTON_SAMPLE               1055
#define IDC_RADIO10                     1056
#define IDC_RADIO11                     1057
#define IDC_RADIO12                     1058
#define IDC_RADIO13                     1059
#define IDC_RADIO14                     1060
#define IDC_RADIO1                      1061
#define IDC_RADIO2                      1062
#define IDC_RADIO3                      1063
#define IDC_RADIO4                      1064
#define IDC_RADIO_SHUIPING2             1065
#define IDC_EDIT1                       1065
#define IDC_EDIT_HOST_IP                1065
#define IDC_EDIT_SECOND                 1065
#define IDC_RADIO_CHUIZHI2              1066
#define IDC_EDIT_PORT                   1066
#define IDC_RADIO_DUIJIAO_UP2           1067
#define IDC_COMBO_ACTION                1067
#define IDC_EDIT2                       1067
#define IDC_EDIT_TIMEOUT                1067
#define IDC_RADIO_RIGHT_UP2             1068
#define IDC_COMBO_RAGE                  1068
#define IDC_EDIT5                       1068
#define IDC_CHECK_ACTION                1069
#define IDC_EDIT_TEXT                   1070
#define IDC_COMBO_BORDER                1074
#define IDC_COMBO_FONT                  1077
#define IDC_EDIT_FONTSIZE               1078
#define IDC_SPIN_SIZE                   1079
#define IDC_COMBO_STYLE                 1080
#define IDC_COMBO_POSITION              1083
#define IDC_TEXTCOLOR                   1085
#define IDC_SPIN4                       1091
#define IDC_CHECK1                      1092
#define IDC_EDIT3                       1095
#define IDC_SPIN5                       1096
#define IDC_EDIT4                       1097
#define IDC_SPIN6                       1098
#define IDC_BACK_COLOR                  1099
#define IDC_SPIN_HEIGHT                 1100
#define IDC_EDIT_HEIGHT                 1102
#define IDC_CHECK_AUTOSIZE              1104
#define IDC_EDIT_NAME                   1105
#define IDC_SPIN_WIDTH                  1108
#define IDC_EDIT_WIDTH                  1109
#define IDC_CONTROLS                    1110
#define IDC_IGNOREREQUIREDCATEGORIES    1111
#define IDC_REQUIREDCATEGORIES          1112
#define IDC_IMPLEMENTEDCATEGORIES       1113
#define IDC_SERVERPATH                  1114
#define IDC_LIST2                       1126
#define IDC_LIST3                       1127
#define IDC_LIST1                       1128
#define IDC_LIST_POINT1                 1128
#define IDC_LIST_POINT2                 1129
#define IDC_LIST_POINT3                 1130
#define ID_UNIT_SAVE                    8800
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_INDICATOR_LOGO               32772
#define ID_FILE_SUMMARYINFO             32773
#define ID_TOOLBOXARROW                 32774
#define ID_TOOLBOXTEXT                  32775
#define ID_TOOLBOXLINE                  32776
#define ID_TOOLBOXCROSS                 32778
#define ID_TOOLBOX_BEELINE              32778
#define ID_TOOLBOXSOLIDRECT             32779
#define ID_TOOLBOXSOLIDROUNDRECT        32780
#define ID_TOOLBOXSOLIDOVAL             32781
#define ID_TOOLBOXSOLIDPOLYGON          32782
#define ID_TOOLBOXCHORD                 32783
#define ID_TOOLBOXPIE                   32784
#define ID_BUTTON32785                  32785
#define ID_TOOLBOXRECTANGLE             32785
#define ID_BUTTON32786                  32786
#define ID_TOOLBOX_ROUNDRECT_NOFILL     32786
#define ID_TOOLBOXOVAL                  32787
#define ID_TOOLBOXPOLYGON               32788
#define ID_TOOLBOXPIPE                  32789
#define ID_TOOLBOX_CONDUIT              32789
#define ID_TOOLBOXBUTTON                32790
#define ID_TOOLBOXBITMAP                32791
#define ID_TOOLBOXSUBBITMAP             32792
#define ID_TOOLBOXGROUP                 32793
#define ID_TOOLBOX_GROUP                32793
#define ID_TOOLBOXDEGROUP               32794
#define ID_TOOLBOX_DEGROUP              32794
#define ID_TOOLBOXCELL                  32795
#define ID_TOOLBOXDECELL                32796
#define ID_TOOLBOXRTCURVE               32797
#define ID_TOOLBOXSTROKE                32798
#define ID_TOOLBOXWARN                  32799
#define ID_TOOLBOXREPORT                32800
#define ID_TOOLBOXOVERSEE               32801
#define ID_TOOLBOXXY                    32802
#define ID_TOOLBOXTEMPLE                32803
#define ID_VIEW_PAPERCOLOR              32804
#define ID_OBJECT_LINECOLOR             32805
#define ID_OBJECT_FILLCOLOR             32806
#define ID_FORMATTING_FONT              32807
#define ID_FORMATTING_SIZE              32808
#define ID_FORMATTING_COLOR             32809
#define ID_FORMATTING_BOLD              32810
#define ID_FORMATTING_ITALIC            32811
#define ID_FORMATTING_UNDERLINE         32812
#define ID_FORMATTING_LINE_COLOR        32814
#define ID_FORMATTING_BACK_COLOR        32815
#define ID_OBJECT_MOVETOFRONT           32816
#define ID_OBJECT_MOVETOBACK            32817
#define ID_OBJECT_MOVEFORWARD           32818
#define ID_OBJECT_MOVEBACK              32819
#define ID_LINE_WIDTH                   32820
#define ID_LINE_STYPE                   32821
#define ID_LEFTARROW_STYLE              32822
#define ID_RIGHTARROW_STYLE             32823
#define ID_DRAW_CURVE                   32851
#define ID_LINE_WIDTH_2                 32853
#define ID_VIEW_FORMAT                  32854
#define ID_VIEW_WORKSPACE               32855
#define ID_VIEW_TOOLBOX                 32856
#define ID_VIEW_GRID                    32857
#define ID_VIEW_SHOWOBJECTS             32858
#define ID_INSERT_FILE                  32859
#define ID_INSERT_CHART                 32860
#define ID_INSERT_OLE_FILE              32861
#define ID_SETTING_PAGE_COLOR           32862
#define ID_TEST                         32864
#define ID_DRAW_SELECT                  32865
#define ID_EDIT_PROPERTIES              32870
#define ID_SETTING_PAGE_SIZE            32872
#define ID_TOOLBOX_ARROW                32873
#define ID_OBJECT_LOADSUB               32876
#define ID_ALIGN_LEFT                   32877
#define ID_ALIGN_RIGHT                  32878
#define ID_ALIGN_TOP                    32879
#define ID_ALIGN_BOTTOM                 32880
#define ID_ALIGN_LEFTRIGHT              32881
#define ID_ALIGN_TOPBOTTOM              32882
#define ID_ALIGN_CENTER                 32883
#define ID_ALIGN_HORZ                   32884
#define ID_ALIGN_VERT                   32885
#define ID_ROTATE                       32886
#define ID_ALIGN_SAME                   32887
#define ID_ALIGN_SAME_LEFTRIGHT         32889
#define ID_ALIGN_SAME_TOPBOTTOM         32890
#define ID_INSERT_ACTIVEX               32891
#define ID_PUPOP_ACTIVE                 32892
#define ID_POPUP_CLOSE                  32893
#define ID_POPUP_PROPERTY               32894
#define ID_POPUP_VIEW_PROPERTY          32895
#define ID_POPUP_MIN                    32896
#define ID_TOOLBOX_QIE                  32900
#define ID_TIME_VIEW                    32901
#define ID_TIME_VIEWCLOSE               32902
#define ID_OnSimulation                 32905
#define ID_OnGenus                      32906
#define ID_MANIPULATE                   32907
#define ID_FLAT_TAB_PROP                32908
#define ID_demo                         32909
#define IDC_BAR_TASKLIST                0xE11F
#define ID_MOUSPOINT                    59143
#define ID_MOUSCAPTION                  59144
#define IDW_TABDOCKBAR                  59502

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32910
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
